# Generated by Django 4.2 on 2025-08-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalNote',
            new_name='MedicalRecord',
        ),
    ]
