# Generated by Django 4.2 on 2025-08-22 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_medicalnote_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 8, 22)),
            preserve_default=False,
        ),
    ]
