# Generated by Django 4.2 on 2025-08-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='note',
            new_name='notes',
        ),
    ]
